package io.savor.common.exceptions;